# Generated by Django 2.2.3 on 2019-08-07 23:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190807_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
