# Generated by Django 2.2.3 on 2019-08-08 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190807_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='api.Client'),
        ),
    ]
